- name: Run group-level tasks on "{{ target_group }}"
  hosts: "{{ target_group }}"
  gather_facts: no
  tasks:
    - name: Include fetch_existing_pwd
      include_role:
        name: 1fetch_existing_pwd

    - name: Include host-level tasks
      include_tasks: tasks/host_rotate_wrapper.yaml
