---
- name: Apply Password Change
  hosts: all
  gather_facts: false
  run_once: true

  vars:
    instance: "{{ instance }}"

  vars_files:
    - config/{{ instance }}.yaml

  tasks:
    - name: Apply password change
      include_role:
        name: apply_password_change
