---
- name: Apply Password Change
  hosts: all
  gather_facts: false
  run_once: true

  vars_files:
    - config/{{ instance }}.yaml

  tasks:
    - name: Apply password change
      include_role:
        name: apply_password_change

    - name: Show final results
      debug:
        var: password_change_results

    - name: Save password change results
      copy:
        dest: "/tmp/password_rotation_state.json"
        content: "{{ password_change_results | to_nice_json }}"
        mode: "0644"
      delegate_to: localhost
      run_once: true
