- name: Rotate passwords for each DB user
  hosts: all
  gather_facts: no
  run_once: true

  roles:
    - fetch_generate_passwords
    - rotate_passwords_db
    - update_secret_server
    - rollback_db_passwords
    - send_email_notification
