---
- name: Fetch and Generate Passwords with OLAM Update
  hosts: all
  gather_facts: no
  run_once: true

  vars_files:
    - config/{{ instance }}.yaml

  tasks:
    - name: Fetch passwords from Secret Server, Generate new passwords, and Update OLAM Credentials
      include_role:
        name: fetch_generate_passwords
