- name: Rotate passwords for each OS user
  hosts: all
  gather_facts: no
  run_once: true

  roles:
    - fetch_generate_passwords
    - rotate_passwords_os
    - update_secret_server
    - rollback_os_passwords
    - send_email_notification