---
- name: Fetch a password from Secret Server, reset password on target hosts, and send email
  hosts: all
  gather_facts: false
  
  vars_files:
    - vars/variables.yaml
  
  vars:
   final_password: "{{ lookup('password', '/dev/null', length=16, special_chars='@$#*') }}"

  roles:
    - role: password_from_secret_server
      delegate_to: localhost  
      run_once: true

    - role: password_reset

    - role: update_password
      delegate_to: localhost  
      run_once: true

    - role: email_notification
      delegate_to: localhost  
      run_once: true 
