- name: Rotate passwords for each inventory group
  hosts: all
  gather_facts: no
  tasks:

    - name: Debug - Show inventory groups
      run_once: true
      debug:
        msg: "Processing inventory group: {{ group_names }}"

    - name: Debug - Show hosts in each group
      debug:
        msg: "Hosts in group {{ group_names[0] }}: {{ groups[group_names[0]] }}"
      run_once: true

    - name: Generate a new password for the group
      run_once: true
      set_fact:
        final_password: "{{ lookup('password', '/dev/null length=16 chars=ascii_letters,digits') }}"

    - name: Debug - Show generated password for the group
      debug:
        msg: "Generated password for group {{ group_names[0] }}: {{ final_password }}"
      run_once: true

    # - name: Rotate password on each host
    #   include_tasks: user_password_rotate.yaml
    #   vars:
    #     final_password: "{{ final_password }}"
