---
- name: Update Secret Server
  hosts: localhost
  gather_facts: false

  vars_files:
    - config/{{ instance }}.yaml

  tasks:

    - name: Read workflow state
      slurp:
        src: /tmp/password_rotation_state.json
      register: state_file

    - name: Parse workflow state
      set_fact:
        password_rotation_items: "{{ state_file.content | b64decode | from_json }}"

    - name: Update Secret Server
      include_role:
        name: update_secret_server

    - name: Show final state
      debug:
        var: password_rotation_items

    - name: Save workflow state
      copy:
        dest: /tmp/password_rotation_state.json
        content: "{{ password_rotation_items | to_nice_json }}"
        mode: "0644"
