- name: Update Secret in Secret Server
  hosts: localhost
  gather_facts: no
  vars:
    secret_id: 18830

  tasks:
    - name: Set variables for API call
      set_fact:
        api_url: "http://centroid.secretservercloud.com/api/v1/secrets/{{ secret_id }}"
        token: "AgLbWy-NEvd3Xivp5EIuZZm2yovywO5zVPAdcpGErhiiD5qyByTOcM9J7R9ePTg5yp5_p-GqkWHhwL7S6rKrv-sYOw7ukRKH36y426_cv0UeAu5OpfQQ0mWWzrHTdZ0MPrpqThJhmAoZWEbOV_4E2O6lbGn9DzxigMYrSUrAgLw6x98Ekznh3LGnlOkjCVeWHOh9KJSKFPHsbz5Rb_a-MLOmUAfyTdt9j2-0DCrg_7SmA_43YDYjrn3myJeheQX4BJ5bV_JvhYRxkUpDtbwjc1Lr0AerZ0jW3MlOFuX0kNdyiqZ7x4KZRhErzYstSPkb2yuFxeB2BmzWZqdoJICM4X5UMDcEmRd0tc5Zou2pIswQLMR4fqb_iucHRycHJJSghxX0xHm2AcSlYFQOq5IOX3iyu-FHOizgxbipfpOkcCudmv2iSdnmlLbDUVmC4ufXjcKr6-smqpEaA7YtUATmVArhpTTTc2v4ngUJv09nLf9ionKwQ2QT_Yrah3O8G_jN-ZjsjC2KGkJMkEjw1prOC85iYiZjMRO-0PZDSKwVrddi67yxvzkqSu-lX__gawBlVFHqOCR4aRIjCy2Mdzbx1Ljeg229crSFKpHktmn7COYwI6rcSpGTRejDDdlABnv8ltEfwXLD8Ov9B0AZMACj2rV7-_EzMzek4SbNd8MFhCD4defEb-br_lKeA8oO1HMS50vGiaRu1CTNX1jYmRn_xpz9j7wJSsobBcNHApAY3vLhtg"
#curl -v -H "Authorization: Bearer AgLbWy-NEvd3Xivp5EIuZZm2yovywO5zVPAdcpGErhiiD5qyByTOcM9J7R9ePTg5yp5_p-GqkWHhwL7S6rKrv-sYOw7ukRKH36y426_cv0UeAu5OpfQQ0mWWzrHTdZ0MPrpqThJhmAoZWEbOV_4E2O6lbGn9DzxigMYrSUrAgLw6x98Ekznh3LGnlOkjCVeWHOh9KJSKFPHsbz5Rb_a-MLOmUAfyTdt9j2-0DCrg_7SmA_43YDYjrn3myJeheQX4BJ5bV_JvhYRxkUpDtbwjc1Lr0AerZ0jW3MlOFuX0kNdyiqZ7x4KZRhErzYstSPkb2yuFxeB2BmzWZqdoJICM4X5UMDcEmRd0tc5Zou2pIswQLMR4fqb_iucHRycHJJSghxX0xHm2AcSlYFQOq5IOX3iyu-FHOizgxbipfpOkcCudmv2iSdnmlLbDUVmC4ufXjcKr6-smqpEaA7YtUATmVArhpTTTc2v4ngUJv09nLf9ionKwQ2QT_Yrah3O8G_jN-ZjsjC2KGkJMkEjw1prOC85iYiZjMRO-0PZDSKwVrddi67yxvzkqSu-lX__gawBlVFHqOCR4aRIjCy2Mdzbx1Ljeg229crSFKpHktmn7COYwI6rcSpGTRejDDdlABnv8ltEfwXLD8Ov9B0AZMACj2rV7-_EzMzek4SbNd8MFhCD4defEb-br_lKeA8oO1HMS50vGiaRu1CTNX1jYmRn_xpz9j7wJSsobBcNHApAY3vLhtg" https://centroid.secretservercloud.com/api/v1/secrets/18830

    # - name: Retrieve existing secret
    #   uri:
    #     url: "{{ api_url }}"
    #     method: GET
    #     headers:
    #       Authorization: "Bearer {{ token }}"
    #     return_content: yes
    #   register: existing_secret

    - name: Retrieve the updated secret
      uri:
        url: "{{ api_url }}" #url: "{{ secret_server_url }}/secrets/{{ secret_id }}"
        method: GET
        headers:
          Authorization: "Bearer {{ token }}"
          Content-Type: "application/json"
      register: get_secret_response
      failed_when: get_secret_response.status != 200 

    - name: Update the secret's name
      uri:
        url: "{{ api_url }}"
        method: PUT
        headers:
          Authorization: "Bearer {{ token }}"
          Content-Type: "application/json"
        body_format: json
        body:
          id: "{{ existing_secret.id }}"
          Password: "UpdatedPassword"  # Update as necessary
      register: updated_secret

    - debug:
        msg: "Updated Secret Name is now {{ updated_secret.Password }}"
