---
- name: Update datasource password
  hosts: all
  gather_facts: false
  run_once: true

  vars:
    instance: "{{ instance }}"

  vars_files:
    - config/{{ instance }}.yaml

  tasks:
    - name: Update datasource password
      include_role:
        name: update_datasource_password
