- name: Debug inventory host and its group names
  debug:
    msg: "Host: {{ inventory_host }}, Groups: {{ hostvars[inventory_host]['group_names'] }}"

- name: Set group name (assuming 1 group per host)
  set_fact:
    user_group: "{{ hostvars[inventory_host]['group_names'][0] }}"

- name: Set user data from the group variable
  set_fact:
    user_list: "{{ hostvars[inventory_host][user_group]['users'] | default([]) }}"


- name: Debug users pulled from group
  debug:
    var: users


- name: Loop through users and include password rotation flow
  include_tasks: rotate_one_user.yaml
  loop: "{{ user_list }}"
  loop_control:
    loop_var: user_entry
