---
- name: Validate APPS database login
  shell: |
    cd /tmp
    source {{ hostvars[target_host].EBS_ENV_FILE }} run
    sqlplus -s apps/{{ target_password }}@{{ hostvars[target_host].DB_SID }} <<EOF
    set heading off feedback off
    select 'VALID' from dual;
    exit;
    EOF
  args:
    executable: /bin/bash
  register: validation
  changed_when: false
  failed_when: "'VALID' not in validation.stdout"
  delegate_to: "{{ target_host }}"
  when: operation_type == 'rotate'