---
- name: Get APPS user details
  set_fact:
    apps_user: >-
      {{
        hostvars[target_host].users
        | selectattr('user', 'equalto', 'APPS')
        | first
      }}

- name: Resolve generated password from OLAM
  set_fact:
    final_password: >-
      {{ lookup('vars', hostvars[target_host].olam_fields.apps_pass_gen) }}

- name: Update password in Secret Server
  include_role:
    name: update_password
  vars:
    group_name: "{{ group_name }}"
    secret_name: "{{ apps_user.secret_name }}"
    secret_id: "{{ apps_user.secret_id }}"
    final_password: "{{ final_password }}"

# - name: Send Email Notification
#   include_role:
#     name: send_email_notification
#   vars:
#     group_name: "{{ group_name }}"
